general:
  local_ip: 000.000.000.000
# Should we use this DB or a different one?
mongodb:
  host: mongodb://IP:27017/
  db: db_name
  db_dev: db_name_dev
  collection: collection_name
api:
  allowed_tokens:
    - token1xyz
    - token2a3f
    - token3ai7
webhooks:
  discord:
    use_discord: false
    moderation_urls:
      - https://discord.com/api/webhooks/A
      - https://discord.com/api/webhooks/A